### ISSUE TITLE
No gif in the readme ?

### ISSUE THREAD

**Issue by Anzumana** [karlch/vimiv#1]

**Comment by karlch** [comment]
Do I understand this correctly, you want me to add something like "supports animated gifs" to the readme?

**Comment by Anzumana** [comment]
Just include a small screencast like here https://github.com/tmux-plugins/tmux-resurrect or  with a gif like here https://github.com/easymotion/vim-easymotion.

**Comment by karlch** [comment]
I don't think a screencast is worth the hassle, I will add some screenshots with the release of version 0.3, which is currently under heavy development, though.

**Comment by karlch** [comment]
Note that I actually ended up doing this for [the new qt version](https://github.com/karlch/vimiv-qt), thanks for the idea, better late than never I guess :smiley:
