### ISSUE TITLE
Filter files and directories

### ISSUE THREAD

**Issue by mardukbp** [karlch/vimiv#11]
I have several directories, whose name contains the same string, e.g. "April". If I enter `/April` vimiv will visit the first result that matches. It would be great if instead it filtered the current directory and only displayed matching files and directories.

**Comment by karlch** [comment]
Not sure if I would like to filter the complete filelist. One might want to simply find a starting point in the current filelist and then continue normally.

Navigating results would definitely be nice though.

**Comment by mardukbp** [comment]
I like the way that [muCommander](http://www.mucommander.com/) handles this. You have the directory listing, type "April" and then you can only select the matching entries, with the others being grayed-out.

**Comment by karlch** [comment]
Sounds interesting, I will definitely implement some type of optical indicator for the search results. They will then still be navigatable via N and P, not with the standard scrolling keys as I think one might want to navigate something else.

I will need some time on this one though and I am a bit busy the next weeks...

**Comment by karlch** [comment]
Alright, search results are now visually highlighted by a configurable markup string. You can navigate them via N and P (and obviously change the keybindings to whatever suits your taste).

Hope this helps. I might implement fancier stuff sometime, but Issue #12 definitely has priority at the moment and new features will have to wait until that stands. Closing for now.

**Comment by mardukbp** [comment]
Great! Thank you very much!
