### ISSUE TITLE
install to /usr/local

### ISSUE THREAD

**Issue by aeosynth** [karlch/vimiv#18]
i `chown` `/usr/local` out of habit from using homebrew on osx; if you could change vimiv to install their, installation would be easier for me

**Comment by karlch** [comment]
I am afraid I will not do that as it violates the arch linux packaging standards.
See: https://wiki.archlinux.org/index.php/Arch_packaging_standards#Package_etiquette

I don't think changing one line in the Makefile is much of a deal-breaker though.

**Comment by aeosynth** [comment]
the arch package can install to another location. yeah it's not much of an issue, just convenience.

**Comment by karlch** [comment]
You are right, it could, but it is obviously more convenient for me this way. Sorry :smiley:
