### ISSUE TITLE
delete key should ask for comfirmation

### ISSUE THREAD

**Issue by carnager** [karlch/vimiv#3]
Right now vimiv will simply delete the file, which could lead to accidently deleted images.
Either show a comfirmation dialog (not very vim-like) or use something like the proposed #2 

The same applies for stuff like flipping.

**Comment by karlch** [comment]
As the key does not delete the image but move it to ~/.vimiv/Trash I don't think much harm could be done. For flipping and so on one could just flip again and the image would be back to normal, I don't see how this could be a problem.

But as I accepted the feature request for a command mode you could just bind those things to keys that don't exist and always use the commands.

**Comment by karlch** [comment]
Closing as #2 was implemented.
