### ISSUE TITLE
can't start over run dialog with ~/.vimiv/vimivrc

### ISSUE THREAD

**Issue by atommixz** [karlch/vimiv#30]
I'm just copy /etc/vimiv/vimivrc to ~/.vimiv/vimivrc and trying run it over lxqt-runner, but nothing happens. It's only run in console. If I remove ~/.vimiv/vimivrc, it's running over lxqt-runner too, I can't understand how I should debugging it.

**Comment by karlch** [comment]
Would you mind sharing some information about your setup? OS and DE/WM would be nice to know so I can try to reproduce. Would running lxqt-runner from the terminal be possible and show any error messages?

I guess lxqt-runner opens vimiv via its .desktop file, but for me this works fine with ~/.vimiv/vimivrc using rofi -run drun.

**Comment by atommixz** [comment]
ArchLinux fresh, LXQT, lxqt-runner-0.11.0-1, vimiv-0.7.1-1

There is no output from lxqt-runner in console, also no -h, no man
also i try run in lxqt-runner over command '/usr/bin/vimiv', but nothing.
sometimes I can see process, but no gui:
`atommixz 13888  0.3  0.4 245020 35316 ?        S    19:17   0:00 /usr/bin/python3 /usr/bin/vimiv`

works with 'rofi -show run'

**Comment by karlch** [comment]
I am sorry, I cannot reproduce the problem on a fresh lxqt install under arch linux. Without any error messages and the possibility to reproduce, there is really not much I can do.

You could try it from a unconfigured new user just to see if it might relate to one of your settings, although I highly doubt it. This really should not be happening...

**Comment by atommixz** [comment]
I cannot reproduse it with new user. U can close it.
