### ISSUE TITLE
Use freedesktop.org's Thumbnail Managing Standard

### ISSUE THREAD

**Issue by woefe** [karlch/vimiv#37]
Vimiv currently uses a custom mechanism to manage its thumbnails. For better integration into many GNU/Linux Desktop Environments, vimiv should adhere to the Thumbnail Managing Standard specified by freedesktop.org. The standard is described [here](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html).

If you think that implementing this standard is a good idea, I am willing to implement it and submit a pull request.

**Comment by karlch** [comment]
Sounds good and a PR is more than welcome :smiley:
