### ISSUE TITLE
Use freedesktop.org's Trash specification

### ISSUE THREAD

**Issue by woefe** [karlch/vimiv#38]
Vimiv currently uses a custom mechanism to manage its trash. For better integration into many GNU/Linux Desktop Environments, vimiv should adhere to freedesktop.org's Trash specification. The standard is described [here](https://standards.freedesktop.org/trash-spec/trashspec-latest.html).

If you think that implementing this standard is a good idea, I am willing to implement it and submit a pull request.

**Comment by karlch** [comment]
Once again, I agree!
