### ISSUE TITLE
Additional XDG_*_HOME changes

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv#40]
Additionally to the changes according to the freedesktop standard mentioned in #37 and #38 it makes sense to:
* Look for configuration files (vimivrc and keys.conf) in XDG_CONFIG_HOME/vimiv/
* Save data, namely history, logfile and Tags in XDG_DATA_HOME/vimiv/

At least temporarily the current and the proposed new standard should be supported, possibly with a deprecation warning at start-up.

What do you think @popeye123 ?

**Comment by popeye123** [comment]
Yes, we should do this. The [basedir-spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) specifies even more $XDG_* variables, but I am not sure if we need to support all of them.
Vimiv should look for config files in all of the following directories and override the values of  a previously read file.

1. `/etc/vimiv`
2. `XDG_*/vimiv/` (or `~/.config/vimiv`)
3. `~/.vimiv`
4. `--config` commandline parameter

This can be implemented using `configparser.read([filenames])` ([documentation](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read)) and would clean up the current configparser implementation.

**Comment by karlch** [comment]
Should be completed with the commits referenced above.
