### ISSUE TITLE
Disable the auto-save when rotate (or flip)

### ISSUE THREAD

**Issue by 22dm** [karlch/vimiv#48]
(English is not my native language; please excuse typing errors.)
Rotating a jpg flie is NOT lossless, so I don't want it automatically save it. I have read the docs and it seems that there isn't a way to config it.
I have commented the line "im.save(filename, **kwargs)" in imageactions.py and it works as I want. But why not add a setting to configure it? I'll be glad if you could consider to add it.

**Comment by karlch** [comment]
I can definitely add this option :smiley:
But as you have found a temporary workaround, I would ask for a bit of patience. I would like to get PR #47 in before and I am currently trying a rewrite of the manipulate and rotate/flip part using GdkPixbuf instead of PIL according to #36 which would affect this directly as well.

Back on topic, do you know why saving is not losless? I would like to fix this, too. Do you think adding quality=100 would help?

**Comment by 22dm** [comment]
Thanks for your reply. I don't know much about the jpeg lossless rotation. But I found that even in gimp, use quality=100 to export the jpg file will make the file as twice large as the original file and still not "lossless" but the "loss" is "less". In vimiv, the jpg file after rotation will be only half large as the original file. But I tried to search in Google and It seems that there still have some way to rotate jpg file losslessly.
By the way, I use`compare -compose src A.jpg B.jpg difference.png` to diff image files.

**Comment by karlch** [comment]
Thanks for your research, much appreciated!

I will take a deeper look into this after the stuff mentioned above. Updates to come :smile:

**Comment by karlch** [comment]
I suspect you never try to rotate/flip multiple (marked) images at the same time or use rotate/flip in thumbnail mode?

Both of these currently rely on being able to edit the file itself and the first one would make no sense at all if one does not want to edit the file.

Therefore, is it okay if I disable these two features if the "autosave_images" setting is False?

**Comment by 22dm** [comment]
Yeah, I think it's okay. Thanks. And I think it would be better if I could save the file using ':w' after rotate when the "autosave_images" is setting to False, just like vim.

**Comment by karlch** [comment]
Okay, I have implemented this (and a lot more) over the past few days. The changes have been pushed to the [test-autosave branch](https://github.com/karlch/vimiv/tree/test-autosave).

I felt the need to change the settings infrastructure and therefore renamed a few settings. The documentation will be updated as soon as I merge this into master but the default config included should work fine. Feel free to test and give me some feedback.

Note that the dependencies have changed: PIL is now dropped, instead gexiv2 is optional for exif support. To build the c-extension you will need the "python-dev" package if on a debian-based system.

The plan is to do some more testing with all these changes and get them into master before the week-end. After this is merged I will close this issue and open a new one for lossless rotation/flipping.

**Comment by 22dm** [comment]
I have tried it and it works just fine, thanks.

**Comment by karlch** [comment]
Merged into master and therefore closing this.

Opened #50 for lossless transforming of images.

**Comment by symbioquine** [comment]
I like vimiv in general, but this issue completely broke my trust. I was very lucky to be able to recover the original images from the camera card. Autosaving/overwriting the original image with a lower quality version should **definitely** not be the default behavior in an image viewer!

**Comment by karlch** [comment]
Sorry to hear this! Personally I always found it quite useless to rotate an image and then not save the state, but the default could certainly be changed. This would then happen [here](https://github.com/karlch/vimiv-qt), I will think about it.

Thanks for your comment!
