### ISSUE TITLE
Link to docs is broken

### ISSUE THREAD

**Issue by sanjayankur31** [karlch/vimiv#53]
Heya - thanks for the new release! I'll submit a package for review in Fedora soon. In the meantime, I was looking for the docs and noticed that the link to the docs returns a 404 error: http://karlch.github.io/vimiv/documentation/

**Comment by karlch** [comment]
Unfortunately I will have to release a follow-up in a few moments as I forgot about removing the dependency to "pillow" in setup.py...

Wow, this is weird, it looks like the complete homepage is rather broken, I have no idea why and I will have to look into this. Thanks for reporting.

**Comment by karlch** [comment]
Should be fixed, the problem was setting baseurl in the _config.yml of the website although Github Pages does this automatically. Funny that it worked before and suddenly broke. Big shoutout to Github support for finding this issue quickly :smiley:

**Comment by sanjayankur31** [comment]
Oh? Weird. I'm still getting the same 404 error somehow..

**Comment by karlch** [comment]
This is really weird, works without the trailing "/" in your link, I only tested it from the website itself, will have to check all references I use...

**Comment by sanjayankur31** [comment]
haha! Yeh! That's a weird one! I wouldn't have thought that a slash would make so much of a difference but then, I'm not exactly a web dev. If I come acorss any other links, I'll open PRs with changes :)

Thanks again :)

**Comment by karlch** [comment]
If you haven't found any more issues, I would close this.

As there were two bugfixes (fullscreen and temp-basedir) and the links in the man pages were wrong, I would release another follow-up sometime soon. Hopefully updating the Fedora package is not much work.

**Comment by sanjayankur31** [comment]
Yeh, it isn't much work. No worries. Closing this now.

**Comment by sanjayankur31** [comment]
vimiv is on release-monitoring.org already, so I'll get a new bug informing me of an updated version :)

https://release-monitoring.org/project/16321/
