### ISSUE TITLE
Cropping of Images

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv#54]
I got this feature request per email, main usecase is cropping images quickly after taking a screenshot.

The idea is to enter a "CROP" mode which displays a rectangle to crop the image to. The nodes of the rectangle can be moved with "hjkl" for small steps and "HJKL" for large steps, possibly other keybindings for things like halfing/doubling the size and so forth. The nodes can be switched via "Tab" and "Shift-Tab". Pressing "Return" applies the crop and returns to "Image" mode.

The feature sounds really cool but I have no idea how difficult this would be. If it is too difficult it will not be implemented.

**Comment by Docbroke** [comment]
this can be done using external command. (using import from imagemagick)
```
:!import image.jpg
```

**Comment by karlch** [comment]
That is actually really smart, no idea why I didn't think about this as I use `import` for my screenshots anyway. Not keyboard driven or internal, but definitely very nice, puts the priority of this even lower.

**Comment by karlch** [comment]
Closing as new features will only be implemented in the [Qt port](https://github.com/karlch/vimiv-qt).
