### ISSUE TITLE
hide scrollbar

### ISSUE THREAD

**Issue by Docbroke** [karlch/vimiv#55]
I like to crop images that match my screen size, so that it can be used as wallpaper. For this I zoom the image, remove display-bar with b, and crop using import command from imagemagick. The issue is once zoomed to larger size scroll-bar appears, which I don't know how to remove/hide.

**Comment by karlch** [comment]
The scrollbar autohides for me which I quite like. Do you disable GTK_OVERLAY_SCROLLING? What theme do you use so I can test a bit?

I don't mind adding this as an option if it is easy enough to do.

**Comment by Docbroke** [comment]
Thanks for the tip. I haven't disabled GTK_OVERLAY_SCROLLLING, as far as I can remember, but when I tried 
```
export GTK_OVERLAY_SCROLLING=1
```
scroll-bar did autohide. So this may be disabled from somewhere. Now added this to my startup. Thanks. Closing.
