### ISSUE TITLE
Request: save as

### ISSUE THREAD

**Issue by Najrim** [karlch/vimiv#56]
There seems to be no option to save opened images. It would be useful for when opening images from the internet. Something like `:saveas`.

**Comment by karlch** [comment]
There is `:w` for saving but it currently does not allow writing to a different filename. I agree that this should be changed. Syntax would be as in vim `:w filename`.

**Comment by karlch** [comment]
Closing as this has already been implemented in the [Qt port](https://github.com/karlch/vimiv-qt) and no new features will be implemted here. More details on this decision can be found at the top of the [readme](https://github.com/karlch/vimiv). I hope the new version can be of some use to you, in case anything is missing [please open an issue](https://github.com/karlch/vimiv-qt/issues).
