### ISSUE TITLE
No documentation on dark theme

### ISSUE THREAD

**Issue by Sweenu** [karlch/vimiv#62]
I searched for some time but wasn't able to reproduce the dark theme as seen in the screenshots. Am I missing something?

(Also want to say that I really like vimiv, I'm very glad I found it, it works wonderfully and has a very clean interface compare to programs like sxiv! Good job :) )

**Comment by karlch** [comment]
Styling vimiv is done completely via Gtk(3) themes. The screenshots are done with the [arc theme](https://github.com/horst3180/Arc-theme) in the dark variant. This should probably be mentioned somewhere...

Note that I am currently working on #61 which will allow completely customizing the look of vimiv with its own style sheets.

Thanks a lot for your warm words, much appreciated :smile:

**Comment by Sweenu** [comment]
Thank you!
I didn't know there were themes haha (well I don't use a DE and the number of non-cli apps I use is very limited). Looking forward to seeing the style sheets system.
