### ISSUE TITLE
support raw images

### ISSUE THREAD

**Issue by ninrod** [karlch/vimiv#63]
Hi! thanks for this awesome program. I'd like to see support for raw images. 

I did not see anywhere in the docs where support for this format is mentioned. 

thanks again.

**Comment by karlch** [comment]
Thanks for your warm words, much appreciated!

I am currently rather busy with work but if I have spare time I am working on #61. I will test if I can get this working within the QT framework and support it in the new version. Would you mind adding a raw image in a comment here for testing purposes, as I don't have any myself?

**Comment by tobiasbrummer** [comment]
I second this request. As a photographer I’d like to have a simple image viewer to look at images without much hassle. 
Sample RAW files from the Sony A6300 are available at this site on the bottom half: [http://www.photographyblog.com/reviews/sony_a6300_review/sample_images/](url)

If displaying RAW files directly is too much work, maybe it would be possible to display the embedded JPG preview? This also should be faster.

**Comment by karlch** [comment]
Closing as new features will only be implemented in the [Qt port](https://github.com/karlch/vimiv-qt). The follow-up issue can be found [here](https://github.com/karlch/vimiv-qt/issues/16).
