### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by sanjayankur31** [karlch/vimiv#68]
I haven't been able to figure out how to send an image to the printer from vimiv. I guess a `:hardcopy` command needs to be added?

I haven't looked at Gtk3 in a while, but possibly, it should provide support for printing (or this could be part of the features set for the Qt rewrite?)

**Comment by karlch** [comment]
This shouldn't be too difficult as both frameworks provide printing support. Although I would go the "easy" route and simply show the standard print dialog which would then have to be navigated by the mouse, similar to what the pdf viewer zathura does.

I will add it to the feature list of the rewrite. Unfortunately I won't be working much on this in the next two months as I have a thesis to complete...

**Comment by sanjayankur31** [comment]
:+1: Awesome---that makes sense. Yeh, I have a thesis to write too :laughing: I'll keep an eye out for the new re-write (would you do it in  a new branch) and help out where possible. Thanks again :)

**Comment by karlch** [comment]
The re-write currently exists in a private repo as the code is horribly unfinished. I will make it public as soon as it is somewhat usable and can then give you a quick heads up if you like. Thanks for offering your help!

I didn't want to do it in a new branch as the two codes would not share code history anyway and I may want to keep the then more or less unmaintained Gtk version for those who do not want to go with Qt only doing major bugfixes.

**Comment by karlch** [comment]
Closing as this has already been implemented in the [Qt port](https://github.com/karlch/vimiv-qt) and no new features will be implemented here. Hope this works well for you :)
