### ISSUE TITLE
Ctrl P (and other plugin) support?

### ISSUE THREAD

**Issue by sanjayankur31** [karlch/vimiv#69]
I was working with a lot of files today and it hit me that a Ctrl P type command (like the plug-in for Vim) would be most useful. I wonder how hard it'll be to add. 

Would it be easier to support a general plug-in architecture instead---so that users can write their own plug-ins like we do for vim?

**Comment by karlch** [comment]
I honestly never used Ctrl P, so I would have to read up on how many features it actually has.

General plug-in support sounds smart, but would require a lot of thinking and work. Difficulties I can see are:
* Proper plug-in manajement (load, lazy load, ... depending on config)
* Plug in installation and packaging (distro, own plugin manager, manual, ...)

I will add it to the issues of the new version, but with rather low priority.

**Comment by karlch** [comment]
Closing as this is WIP in the [Qt port](https://github.com/karlch/vimiv-qt) and no new features will be implemented here. Follow-up issue including Ctrl-P support [can be found here](https://github.com/karlch/vimiv-qt/issues/62).
