### ISSUE TITLE
Library is always shown even with `--no-library` option

### ISSUE THREAD

**Issue by petobens** [karlch/vimiv#70]
Hi!. I tried running `vimiv --no-library` and even adding `start_show_library: no` to my `vimivrc` file but the library is always shown upon opening. I'm using latest git version.
Thanks in advance for looking into this.

**Comment by karlch** [comment]
Does it also show the library if you add a path to an image to the command? E.g.
`vimiv --no-library Images/my_image.png`

If not, it will always show the library, as there is nothing else to show and the library is the preferred way to open an image, once vimiv has been started.

**Comment by petobens** [comment]
Ok. I was under the impression that `--no-library` would never show the library. The flag is a bit misleading i guess. Don't know if you can/plan to change the behaviour (either by changing the man page or actually never showing the library). Feel free to close. Thanks!

**Comment by karlch** [comment]
Just out of curiosity, what would you display instead? Just a plain background? And how should the user then open images?

**Comment by karlch** [comment]
This makes sense and is already possible in the (private) Qt rewrite, I really have to get this in a usable state :smile:

**Comment by karlch** [comment]
Closing as this has been implemented in the [Qt port](https://github.com/karlch/vimiv-qt) which is now in a much more usable state. No new features will be implemented here. I hope the new version can be of some use to you, in case anything is missing [please open an issue](https://github.com/karlch/vimiv-qt/issues).
