### ISSUE TITLE
:!gimp % doesnt open gimp on current picture?

### ISSUE THREAD

**Issue by thepenguinthatwants** [karlch/vimiv#76]
Hi!

vimiv seems to work vey well on my normal usage but I couldnt get it open current picture for edit. 

:!gimp % did open gimp but it didnt have any picture showing.

Currently using archlinux sway vimiv 0.9.1-2

Could be cool to make own mappings to open pictures for editing etc.

**Comment by karlch** [comment]
Hi, thanks for your feedback!

How exactly did you run the command? I just installed the package from `[community]` and gimp opened the current image as expected, both from image and library mode.

Note that I am now mainly working on [the qt version](https://github.com/karlch/vimiv-qt) which will eventually replace this repository.

**Comment by thepenguinthatwants** [comment]
Hi!

Seems like wayland is just acting weirdly. I could use this quite well in i3wm. So this seems to work well.

But then I noticed that I couldn't map this on key e. Most likely its because of my lack of knowledge.

`e:          !gimp %`

Do you have any tips on how to make this work?

**Comment by karlch** [comment]
Unfortunately that is not possible in this version and I won't be implementing any new features here. It should work in the qt port though which is slowly coming towards feature parity. I will make an AUR package for it soon :tm: 

In any case, you would have to escape the `%` in the form of `%%` as the `%` character is treated specialy by python's configparser.

**Comment by karlch** [comment]
Closing as this works in the [Qt port](https://github.com/karlch/vimiv-qt/issues?q=is%3Aissue+is%3Aclosed) as mentioned before. Hope this is still of some use for you and sorry for the version chaos, cleanup is on the way :smiley:
