### ISSUE TITLE
Suggestions: regarding marks

### ISSUE THREAD

**Issue by elig0n** [karlch/vimiv#78]
It happened that I had some marks set and wanting to rotate an open image it didn't stating that the marked images did, I suggest adding a mark indicator to the status bar perhaps also showing the count of marked files.

Also :mark_clear command because once some files are marked in a directory which isn't currently seen in the file list pane it is impossible to find out via mark_toggle (unless you save a tagfile and examine it). Maybe also a way to quickly jump/navigate between only marked files.

Overall great app!

**Comment by karlch** [comment]
Thanks a lot for your feedback!

All of this makes a lot of sense. Unfortunately I will not be implementing any of this here but instead I added a reference to https://github.com/karlch/vimiv-qt/issues/5 . If you like I can give you a heads-up once this is implemented there. I hope to do marks and tags this week-end. 

Honestly I find the behaviour of rotating all marked images rather weird by now and probably will not implement it again. With the status indicator you mean something that gives you the total number of marked images in addition to the hint if the current image is marked?

**Comment by elig0n** [comment]
> Honestly I find the behaviour of rotating all marked images rather weird by now and probably will not implement it again. With the status indicator you mean something that gives you the total number of marked images in addition to the hint if the current image is marked?

I do not feel it being weird, it can actually be useful when several pictures i.e. taken in a camera aren't in proper orientation.

About status indicator you are correct. Marks can remain in the "background" especially when leaving the directory one can forget they are set, mark some other pictures and then oops! incorrect modifications.
