### ISSUE TITLE
Image order

### ISSUE THREAD

**Issue by kaldown** [karlch/vimiv#79]
Is it possible to change an image order?
Like most recent to be on top.

Thanks.

**Comment by karlch** [comment]
Currently not internally. You should be able to emulate something like this with a shell filter though, if you have a working one. An example for reversing would be running `!ls | tac |`.

I find this an interesting feature though and it could be implemented internally. As I won't be implementing any new features in this port, I opened https://github.com/karlch/vimiv-qt/issues/75.

Thanks for the idea!

**Comment by kaldown** [comment]
Thank you for a nice product, and being responsive ;)

**Comment by karlch** [comment]
I will close this issue as, like mentioned before, I will not be implementing any new features here and I am currently cleaning up the issues here. Sorry for letting your [PR](https://github.com/karlch/vimiv-qt/pull/76) become stale. If you like I can try to rebase it onto the current master or cherry-pick some of your work, of course adding you to the `AUTHORS` file.
