### ISSUE TITLE
Possible to set background on black?

### ISSUE THREAD

**Issue by ReneFroger** [karlch/vimiv#80]
The default color of background in my OS is white (XFCE, with GTK). 
I would like to set black background for Vimiv. But this option is neither listed in documentation or in the default configuration files. 

Would it be possible to add it to Vimiv?

**Comment by karlch** [comment]
Unfortunately vimiv relies completely on the Gtk theme for setting colors and I won't be adding any new features to this port, sorry...

However styling and theming is fully possible in the [qt port](https://github.com/karlch/vimiv-qt/) which is becoming more and more mature and v0.1 should be out soon :tm:

**Comment by karlch** [comment]
Closing as this works in the [Qt port](https://github.com/karlch/vimiv-qt) with the [styling](https://karlch.github.io/vimiv-qt/documentation/configuration/style.html) and no new features will be implemented here. Hope the new version can be of some use to you. Feel free to [open an issue](https://github.com/karlch/vimiv-qt/issues) if anything is missing there.
