### ISSUE TITLE
Keep library and imager viewer in sync

### ISSUE THREAD

**Issue by reneatzi** [karlch/vimiv#81]
**Setup:**
The image viewer and the library are open. The focus is on the library.

**Feature Request:**
It would be great to have an option, that when I press n or p that it also selects the current image in the library and vice versa. So, when I'm moving between files in the library with j and k, that it also automatically selects this item in the image viewer (basically pressing j + l).

**Comment by karlch** [comment]
Thanks for your feature request!

I agree that this is a very useful feature but I will not add any more features to this Gtk version. I have however added this in the [qt port](https://github.com/karlch/vimiv-qt) which I feel has come out very nice. As soon as some more testing and maturing has happened, I will add some more notes on this here. Feel free to give it a shot :smile:

The details on your feature request can be seen in the [changelog of the qt port](https://karlch.github.io/vimiv-qt/changelog.html) (the `--open-selected` flag).

**Comment by reneatzi** [comment]
Thank you for your response and your great work!

I will checkout the qt port

**Comment by karlch** [comment]
Closing as, like mentioned before, new features will only be implemented in the [Qt port](https://github.com/karlch/vimiv-qt) and this has been impemented there.
