### ISSUE TITLE
Can vimiv hav XDG Base Directory instead in  ~/.config

### ISSUE THREAD

**Issue by thepenguinthatwants** [karlch/vimiv#84]
Hi!

I really like using vimiv. but its clutteringmy home folder. Wondering if it could also read from ~/.config folder?

**Comment by karlch** [comment]
It should currently also read the configuration file if it sits in `~/.config/vimiv/vimivrc`, does this also work for you?

Note that I would also recommend using the [qt version if possible](https://github.com/karlch/vimiv-qt/) where the only valid config file is `~/.config/vimiv/vimiv.conf`. By now there is also an [AUR package](https://aur.archlinux.org/packages/vimiv-qt/) for this in case you would like to test it.

**Comment by thepenguinthatwants** [comment]
Yes you are right. Sorry I just read the man page and didnt try it throughly. Sorry.

**Comment by karlch** [comment]
No need to apologize, here to help, glad it works as expected :)
