### ISSUE TITLE
How to move with mouse

### ISSUE THREAD

**Issue by scrouthtv** [karlch/vimiv#86]
Is there any way to configure `vimiv` to move the picture with the mouse when a certain button is held down?

I'm thinking about something similar to how mupdf works:
![mupdf_mouse](https://user-images.githubusercontent.com/23227405/81856421-12eb5380-9561-11ea-905e-1e0a8f97bfe1.gif)

I read that there is a config for keybindings but I couldn't find any movement command.

Any help would be greatly appreciated, thank you :)

**Comment by karlch** [comment]
Thanks for your interest in vimiv and the very clear issue report.

Unfortunately the behaviour you describe is not possible here, but image panning is the default behaviour of the [newer qt port](https://github.com/karlch/vimiv-qt) for the regular left mouse button. Any new features will only be implemented there and I hope the version chaos will be solved at some point. For more information on the new version you can take a look at [this issue](https://github.com/karlch/vimiv/issues/61) or [the information on migrating](https://karlch.github.io/vimiv-qt/documentation/migrating.html).

Would it be feasible for you to switch to the newer port?

**Comment by scrouthtv** [comment]
I just installed the qt port and it works for me as well. Thank you so much!
