### ISSUE TITLE
Issue with thumbnails

### ISSUE THREAD

**Issue by Cryoniq** [karlch/vimiv#89]
Greetings. Is it okay that vimiv generates thumbnails every single time you enter the thumbnail mode even if it already generated them? Like in attached example.

![vimiv](https://user-images.githubusercontent.com/8151682/87241879-fd46bd00-c42f-11ea-8125-f996df079a3a.gif)

**Comment by karlch** [comment]
Thanks for your interest and this nice report.

Vimiv creates the thumbnails in the cache directory if they don't exist. Afterwards they are re-read from the created thumbnail file upon every entry which apparently takes a while. This is solved in a much better way over in the [qt port](https://github.com/karlch/vimiv-qt) where the performance is better in general. In case you don't have strong reasons to stick to the gtk version I would definitely recommend switching. There is also some documentation on [migrating](https://karlch.github.io/vimiv-qt/documentation/migrating.html) available.

As this is fixed over there and not a super severe bug, I will probably not do anything about it here, sorry!
