### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by mardukbp** [karlch/vimiv#9]
It would be great to be able to rename a file in the library. I do this all the time with vim. Thank you for this awesome program!

**Comment by karlch** [comment]
You can currently run an external command to rename the current file, like `:!mv % new_name` or format all files within the current filelist via `:format "formatstring"`.

I made format available in the library, is that what you wanted?

**Comment by mardukbp** [comment]
You are right. `:!mv` is enough for my purposes.
