### ISSUE TITLE
animated png support

### ISSUE THREAD

**Issue by benjaminBrownlee** [karlch/vimiv#90]
It'd be really cool if vimiv could play animated PNGs just like it can for GIFs. I'm not sure how similarly it would be implemented to GIFs, but I'm willing to play around with the GTK python module to try a draft a pull request if this is a desirable feature.

**Comment by karlch** [comment]
Supporting animated PNG's does sound like a very handy feature!

Unfortunately I would not work on any new features here in the legacy Gtk version of vimiv, but would love to see this in the [qt port](https://github.com/karlch/vimiv-qt). Would it be possible for you to switch and play around with Qt instead? I must say the codebase there should also be quite a bit easier to deal with. If you are up for the game, you could just open the same issue over there and we could continue our discussion.

Of course I would also accept a well drafted PR here, but long-term there will be not many improvements here and the development focus has clearly shifted to the rewrite.

**Comment by benjaminBrownlee** [comment]
Oh shoot, I didn't see that the qt migration is being made. I can make an issue/PR over there!
