### ISSUE TITLE
Feature Request: Support '=' as '+'

### ISSUE THREAD

**Issue by mcp292** [karlch/vimiv#92]
Most applications allow `=` in place of `+` to save the user the shift. Since it doesn't seem to be bound, this would nice to have.

**Comment by karlch** [comment]
Hey, thanks for your interest in vimiv and feature request!

Note that development has shifted to the [qt port](https://github.com/karlch/vimiv-qt) and I will unfortunately not add any new features / bindings / commands in this branch and only fix major bugs for some more time. Luckily it is very easy for you to configure this to your liking, just add:
```
equal: zoom_in
```
to the image section of `~/.config/vimiv/keys.conf`.

In the qt port `=` is bound to fit the image. This is more in lign with what I have seen from e.g. sxiv or qutebrowser, where `=` would restore the zoom level, not actually zoom in. But of course changing keybindings in the `keys.conf` is still possible there, just with a bit of a different naming / command scheme. In case you are interested, you can find some information on [migrating](https://karlch.github.io/vimiv-qt/documentation/migrating.html).

Let me know if there is anything I can help you with!

Closing as this will not be changed here as explained.
