### ISSUE TITLE
Toggle hidden files

### ISSUE THREAD

**Issue by Kakupakat** [karlch/vimiv#94]
Please add the possibility to toggle hidden files. Maybe with the keys that [Vifm](https://github.com/vifm/vifm) uses: 

- za toggle visibility of dot files.
- zo show dot files.
- zm hide dot files.

Thank you

**Comment by karlch** [comment]
Thanks for your interest in vimiv!

Unfortunately binding key sequences (i.e. multiple regular keys after one another) is not possible in this deprecated gtk port. However, this works just fine in the newer [qt port](https://github.com/karlch/vimiv-qt) and adding bindings for this would be a matter of minutes. Would it be possible for you to [migrate](https://karlch.github.io/vimiv-qt/documentation/migrating.html)?

I have opened [an issue](https://github.com/karlch/vimiv-qt/issues/372) there for further discussion in case you are interested :blush: I will go ahead and close this one as any further work would only happen in the qt port, sorry if this is a major nuissance!
