### ISSUE TITLE
Crash on large gif file

### ISSUE THREAD

**Issue by anufrievroman** [karlch/vimiv#96]
It looks like large gif file can't be opened ([example](https://github.com/Sweets/dotfiles/blob/master/.wm/schemes/sakura/wallpaper.gif)). However, smaller gif files of a few mb are fine.

**Comment by karlch** [comment]
Thanks for reporting!

I wonder, are you actually using the legacy Gtk version or have you migrated to the newer [Qt port](https://github.com/karlch/vimiv-qt)?

In case you migrated, could you open a bug report there. Then this will be fun to debug, as I cannot reproduce, yet.

In case you are still on Gtk, this unfortunately will be a won't fix here, as the Qt port is [clearly the future](https://github.com/karlch/vimiv/issues/61), and our ressources are unfortunately too small to also concentrate on the legacy codebase atm. Sorry in case relevant!

**Comment by anufrievroman** [comment]
Hi, thank you for answering. Yes, I was on legacy version. Qt port doesn't have this bug. I'll close it then.
