### ISSUE TITLE
Change sorting method in Vimiv

### ISSUE THREAD

**Issue by ReneFroger** [karlch/vimiv#97]
I have some files in a directory. In e.g. file explorer Thunar they are sorted in this order:

> w8.jpg
> w10.jpg 
> w11.jpg
> w89.jpg
> w100.jpg
> Whatsapp.jpg

In most image viewer, when I open the image `w100.jpg`, the next image is `Whatsapp.jpg` to be displayed.
In vimiv, when I view `w100.jpg` file. Then the next image to be shown will be `w10.jpg`. I would expect the file `Whatsapp.jpg`  in alphabetically order. the The way vimiv select the next image in line is very confusing.

For the other fileviewer like feh, you can change the sorting option  with the `-S/--sort option` according to their manual. Would it be possible to enable logical sorting in vimiv, or adjust it via configuration?

**Comment by karlch** [comment]
Hey and thanks for your interest in vimiv!

In case you are actually still using the Gtk version, this will unfortunately not be implemented here. We made the switch to Qt a while ago and are only actively improving this version with limited time, sorry for that.

New features are thus only worked on in the [Qt port](https://github.com/karlch/vimiv-qt). If you are able to make the switch (the Qt version has a bunch of improvements!), this is actually already implemented with the `sort.image_order` and `sort.directory_order` [settings](https://karlch.github.io/vimiv-qt/documentation/configuration/settings.html).

There is [some more information on migrating](https://karlch.github.io/vimiv-qt/documentation/migrating.html) available in the documentation as well. Hope this helps!
